/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 japanese_mask.glb 
Author: Romain Vaysse (https://sketchfab.com/redshell)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/japanese-mask-9a3972e41f4646129245c6acd5a19b71
Title: Japanese Mask
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mask(props) {
  const { nodes, materials } = useGLTF('/japanese_mask.glb')
  return (
    <group  {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.defaultMat} />
      </group>
    </group>
  )
}

useGLTF.preload('/japanese_mask.glb')
