/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 white_tiger_power_ranger.glb 
Author: mohjustic (https://sketchfab.com/mohanm12061997)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/white-tiger-power-ranger-78ff61fd491f433c9870fd167c82645b
Title: White Tiger Power Ranger
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WhiteTiger(props) {
  const { nodes, materials } = useGLTF('/white_tiger_power_ranger.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PolySphere1_2_PolySphere1_20_0.geometry} material={materials.PolySphere1_20} />
      <mesh geometry={nodes.PolySphere1_3_PolySphere1_30_0.geometry} material={materials.PolySphere1_30} />
      <mesh geometry={nodes.PolySphere1_3_PolySphere1_30_0_1.geometry} material={materials.PolySphere1_30} />
      <mesh geometry={nodes.PolySphere1_3_PolySphere1_31_0.geometry} material={materials.PolySphere1_31} />
    </group>
  )
}

useGLTF.preload('/white_tiger_power_ranger.glb')
